-- imagerecord.schema.sql
-- Supabase/PostgreSQL DDL for the "imagerecord" table, tailored to your sample row.

create table if not exists public.imagerecord (
  id          bigint generated by default as identity primary key,
  file_name   text        not null,                      -- full public URL to the image
  event       text,                                      -- e.g. "test", "expo_2025", etc.
  people      jsonb       not null default '{}'::jsonb,  -- map of person-name -> boolean/metadata
  created_at  timestamptz not null default now()
);


-- Example INSERT (people parsed as real JSONB, not a quoted string):
insert into public.imagerecord (file_name, event, people)
values (
  'https://something.supabase.co/storage/v1/object/public/timespace/group_pic_1.jpg',
  'test',
  '{
    "Chris-Evans": true,
    "Chris-Hemsworth": true,
    "Robert-Downey-Jr": true,
    "Scarlett-Johansson": true
  }'::jsonb
);
